package cit.edu.furrevercare.entity;

import com.google.cloud.firestore.annotation.DocumentId;
// Consider adding other annotations like @IgnoreExtraProperties if useful

import java.util.Map;
import java.util.Objects;

public class Resource {

    @DocumentId // Firestore will auto-populate this with the document ID when retrieved
    private String resourceID; // Will be generated by Firestore or set manually
    private String userID;     // To link this resource to a specific user
    private String name;       // e.g., "Happy Paws Vet Clinic", "PetCo Main Street"
    private String type;       // Store as String, corresponds to ResourceType enum on client
    // e.g., "VET", "GROOMER", "PET_STORE"

    // Using a Map for flexible contact details
    // Keys could be "phone", "email", "website", "address", "latitude", "longitude"
    private Map<String, String> contactDetails;

    private String notes;
    private String operatingHours; // e.g., "Mon-Fri 9 AM - 5 PM"

    public Resource() {
        // Default constructor for Firestore
    }

    // Getters and Setters
    public String getResourceID() {
        return resourceID;
    }

    public void setResourceID(String resourceID) {
        this.resourceID = resourceID;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Map<String, String> getContactDetails() {
        return contactDetails;
    }

    public void setContactDetails(Map<String, String> contactDetails) {
        this.contactDetails = contactDetails;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getOperatingHours() {
        return operatingHours;
    }

    public void setOperatingHours(String operatingHours) {
        this.operatingHours = operatingHours;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Resource resource = (Resource) o;
        return Objects.equals(resourceID, resource.resourceID) &&
                Objects.equals(userID, resource.userID) &&
                Objects.equals(name, resource.name) &&
                Objects.equals(type, resource.type) &&
                Objects.equals(contactDetails, resource.contactDetails) &&
                Objects.equals(notes, resource.notes) &&
                Objects.equals(operatingHours, resource.operatingHours);
    }

    @Override
    public int hashCode() {
        return Objects.hash(resourceID, userID, name, type, contactDetails, notes, operatingHours);
    }

    @Override
    public String toString() {
        return "Resource{" +
                "resourceID='" + resourceID + '\'' +
                ", userID='" + userID + '\'' +
                ", name='" + name + '\'' +
                ", type='" + type + '\'' +
                ", contactDetails=" + contactDetails +
                ", notes='" + notes + '\'' +
                ", operatingHours='" + operatingHours + '\'' +
                '}';
    }
}